
---
#Role Java vars

download_url: https://download.java.net/java/GA/jdk16.0.1/7147401fd7354114ac51ef3e1328291f/9/GPL/openjdk-16.0.1_linux-x64_bin.tar.gz
download_folder: /opt
java_name: "{{download_folder}}/jdk-16.0.1"
java_archive: "{{download_folder}}/openjdk-16.0.1_linux-x64_bin.tar.gz"
java_home: /opt/jdk-16.0.1
