---
# vars file for atom

_atom_requirements:
  apt:
    - apt-transport-https

atom_requirements: "{{ _atom_requirements[ansible_pkg_mgr] | default(omit) }}"

_atom_package:
  apt:
    url: 'https://atom.io/download/deb'
    name: atom-amd64.deb

atom_package_url: '{{ _atom_package[ansible_pkg_mgr]["url"] }}'
atom_package: "{{ _atom_package[ansible_pkg_mgr]['name'] }}"


