---
# Ansible role to install basic ubuntu packages
- name: "Install base packages"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 604800
  vars:
    packages:
    - jq
    - vim
    - htop
    - curl
    - wget
    - cifs-utils
    - nfs-common
  

