---
# tasks file for atom

- name: Install requirements
  ansible.builtin.package:
    name: "{{ atom_requirements }}"
    state: present
  when:
    - atom_requirements is defined


- name: Download atom.deb
  ansible.builtin.get_url:
    url: "{{ atom_package_url }}"
    dest: "/tmp/{{ atom_package }}"
    validate_certs: no

- name: Install atom.deb
  ansible.builtin.apt:
    deb: "/tmp/{{ atom_package }}"
    state: present
