---
# tasks file for atom

- name: install requirements
  ansible.builtin.package:
    name: "{{ atom_requirements }}"
    state: present
  when:
    - atom_requirements is defined


- name: download atom
  ansible.builtin.get_url:
    url: "{{ atom_package_url }}"
    dest: "/tmp/{{ atom_package }}"
    validate_certs: no

- name: install atom deb
  ansible.builtin.apt:
    deb: "/tmp/{{ atom_package }}"
    state: present

